In [1]:
import pandas as pd
from histcite.process_table import ProcessTable
from histcite.network_graph import GraphViz
from histcite.compute_metrics import ComputeMetrics

In [2]:
# 读取文件，去重，合并
folder_path = 'dataset'
process = ProcessTable(folder_path)
concated_table = process.concat_table()
concated_table

,doc_index,AU,TI,SO,DT,DE,C3,CR,NR,TC,Z9,J9,PY,VL,BP,DI,UT
0,0,"GLAUERT, JRW; KENNAWAY, JR; SLEEP, MR",DACTL - AN EXPERIMENTAL GRAPH REWRITING LANGUAGE,LECTURE NOTES IN COMPUTER SCIENCE,Article,DACTL; GRAPH REWRITING; COMPUTATIONAL MODEL; P...,University of East Anglia,"BAETEN JCM, 1987, LNCS, V257, P83; BARENDREGT ...",36,9,9,LECT NOTES COMPUT SC,1991,532,378,<NA>,WOS:A1991LE71500041
1,1,"PIELA, PC; EPPERLY, TG; WESTERBERG, KM; WESTER...",ASCEND - AN OBJECT-ORIENTED COMPUTER ENVIRONME...,COMPUTERS & CHEMICAL ENGINEERING,Article,<NA>,Carnegie Mellon University,"Borning Alan, 1979, THESIS STANFORD U; EPPERLY...",19,120,123,COMPUT CHEM ENG,1991,15,53,10.1016/0098-1354(91)87006-U,WOS:A1991FA96900006
2,2,"TEETERS, JL",MDL - A SYSTEM FOR FAST SIMULATION OF LARGE LA...,SIMULATION,Article,MODEL DEVELOPMENT LANGUAGE; SIMULATION LANGUAG...,University of Southern California,"Carey R, 1975, THESIS U MASSACHUSET; DESCHUTTE...",14,1,1,SIMULATION,1991,56,369,10.1177/003754979105600606,WOS:A1991FV44300002
3,3,"MCBRIEN, P; NIEZETTE, M; PANTAZIS, D; SELTVEIT...",A RULE LANGUAGE TO CAPTURE AND MODEL BUSINESS ...,LECTURE NOTES IN COMPUTER SCIENCE,Article,<NA>,University of Liege; University of Manchester,"BERZTISS A, 1986, INFORMATION SYSTEM D; BORGID...",23,6,6,LECT NOTES COMPUT SC,1991,498,307,<NA>,WOS:A1991FW90200015
4,4,"Kottemann, JE; Dolk, DR",Model Integration and Modeling Languages: A Pr...,INFORMATION SYSTEMS RESEARCH,Article,Model management; Model integration; Modeling ...,University of Michigan System; University of M...,"Blanning R. W., 1986, Decision Support Systems...",25,31,31,INFORM SYST RES,1992,3,1,10.1287/isre.3.1.1,WOS:000209837400001
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,1995,"Kanas, A; Kosyakova, Y; Vallizadeh, E","Linguistic Enclaves, Sorting, and Language Ski...",JOURNAL OF IMMIGRANT & REFUGEE STUDIES,Article; Early Access,Destination language acquisition; linguistic e...,Erasmus University Rotterdam; Otto Friedrich U...,"Aksoy C.G., 2020, SSRN ELECT J, DOI [10.2139/s...",49,0,0,J IMMIGR REFUG STUD,<NA>,<NA>,<NA>,10.1080/15562948.2022.2132572,WOS:000876581300001
1996,1996,"Guo, Y; Xu, JF; Chen, C",Measurement of engagement in the foreign langu...,IRAL-INTERNATIONAL REVIEW OF APPLIED LINGUISTI...,Article; Early Access,CFA; EFL classroom learning; foreign language ...,Huazhong University of Science & Technology; W...,"Aubrey S, 2022, RELC J, V53, P519, DOI 10.1177...",73,3,3,IRAL-INT REV APPL LI,<NA>,<NA>,<NA>,10.1515/iral-2021-0118,WOS:000747993700001
1997,1997,"Wang, YB; Liu, FS",Emotional intelligence and second/foreign lang...,LANGUAGE TEACHING RESEARCH,Review; Early Access,emotional intelligence; language learning; met...,Guangdong University of Foreign Studies; Jiang...,"Abdolrezapour P., 2018, CYPRIOT J ED SCI, V13,...",89,0,0,LANG TEACH RES,<NA>,<NA>,<NA>,10.1177/13621688231152627,WOS:000936380600001
1998,1998,"Li, JX; Zhang, EH; Zhang, HH; Gou, HC; Cao, HW",Retrieval practice plus feedback benefits a th...,INTERNATIONAL JOURNAL OF MULTILINGUALISM,Article; Early Access,Retrieval practice; testing effect; learning a...,Chongqing University; Shenyang Normal University,"Abel M, 2020, COGNITION, V201, DOI 10.1016/j.c...",67,0,0,INT J MULTILING,<NA>,<NA>,<NA>,10.1080/14790718.2022.2102172,WOS:000831158400001
1999,1999,"Calder, SD; Brennan-Jones, CG; Robinson, M; Wh...",How we measure language skills of children at ...,INTERNATIONAL JOURNAL OF SPEECH-LANGUAGE PATHO...,Article; Early Access,Developmental language disorder; identificatio...,University of Tasmania; Curtin University; Tel...,"Adams C., 2001, ASSESSMENT COMPREHEN; American...",53,0,0,INT J SPEECH-LANG PA,<NA>,<NA>,<NA>,10.1080/17549507.2023.2171488,WOS:000935546000001

In [3]:
# 提取并解析所有文献的参考文献
reference_table = process.generate_reference_table(concated_table['CR'])
reference_table

,AU,PY,J9,VL,BP,DI,doc_index
0,BAETEN JCM,1987,LNCS,257,83,None,0
1,BARENDREGT HP,1987,LECT NOTES COMPUT SC,259,141,None,0
2,BARENDREGT HP,1989,PARALLEL COMPUT,9,163,10.1016/0167-8191(89)90126-9,0
3,DERSHOWITZ N,1989,HDB THEORETICAL CO B,<NA>,<NA>,None,0
4,EHRIG H,1979,LNCS,73,83,None,0
...,...,...,...,...,...,...,...
69185,Wiig E. H.,2013,CLIN EVALUATION LANG,<NA>,<NA>,None,1999
69186,Yarian M,2021,COMMUN DISORD Q,42,111,10.1177/1525740119868238,1999
69187,Zimmerman I. L.,2011,PRESCHOOL LANGUAGE S,<NA>,<NA>,None,1999
69188,Zubrick SR,2015,PLOS ONE,10,<NA>,10.1371/journal.pone.0135612,1999
69189,Zupan B,2021,AUST J RURAL HEALTH,29,880,10.1111/ajr.12766,1999

In [4]:
# 识别引文关系
citation_table = process.process_citation(reference_table)
citation_table

,doc_index,AU,TI,SO,DT,DE,C3,CR,NR,TC,...,J9,PY,VL,BP,DI,UT,reference,citation,LCR,LCS
0,0,"GLAUERT, JRW; KENNAWAY, JR; SLEEP, MR",DACTL - AN EXPERIMENTAL GRAPH REWRITING LANGUAGE,LECTURE NOTES IN COMPUTER SCIENCE,Article,DACTL; GRAPH REWRITING; COMPUTATIONAL MODEL; P...,University of East Anglia,"BAETEN JCM, 1987, LNCS, V257, P83; BARENDREGT ...",36,9,...,LECT NOTES COMPUT SC,1991,532,378,<NA>,WOS:A1991LE71500041,None,None,0,0
1,1,"PIELA, PC; EPPERLY, TG; WESTERBERG, KM; WESTER...",ASCEND - AN OBJECT-ORIENTED COMPUTER ENVIRONME...,COMPUTERS & CHEMICAL ENGINEERING,Article,<NA>,Carnegie Mellon University,"Borning Alan, 1979, THESIS STANFORD U; EPPERLY...",19,120,...,COMPUT CHEM ENG,1991,15,53,10.1016/0098-1354(91)87006-U,WOS:A1991FA96900006,None,None,0,0
2,2,"TEETERS, JL",MDL - A SYSTEM FOR FAST SIMULATION OF LARGE LA...,SIMULATION,Article,MODEL DEVELOPMENT LANGUAGE; SIMULATION LANGUAG...,University of Southern California,"Carey R, 1975, THESIS U MASSACHUSET; DESCHUTTE...",14,1,...,SIMULATION,1991,56,369,10.1177/003754979105600606,WOS:A1991FV44300002,None,None,0,0
3,3,"MCBRIEN, P; NIEZETTE, M; PANTAZIS, D; SELTVEIT...",A RULE LANGUAGE TO CAPTURE AND MODEL BUSINESS ...,LECTURE NOTES IN COMPUTER SCIENCE,Article,<NA>,University of Liege; University of Manchester,"BERZTISS A, 1986, INFORMATION SYSTEM D; BORGID...",23,6,...,LECT NOTES COMPUT SC,1991,498,307,<NA>,WOS:A1991FW90200015,None,None,0,0
4,4,"Kottemann, JE; Dolk, DR",Model Integration and Modeling Languages: A Pr...,INFORMATION SYSTEMS RESEARCH,Article,Model management; Model integration; Modeling ...,University of Michigan System; University of M...,"Blanning R. W., 1986, Decision Support Systems...",25,31,...,INFORM SYST RES,1992,3,1,10.1287/isre.3.1.1,WOS:000209837400001,None,None,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,1995,"Kanas, A; Kosyakova, Y; Vallizadeh, E","Linguistic Enclaves, Sorting, and Language Ski...",JOURNAL OF IMMIGRANT & REFUGEE STUDIES,Article; Early Access,Destination language acquisition; linguistic e...,Erasmus University Rotterdam; Otto Friedrich U...,"Aksoy C.G., 2020, SSRN ELECT J, DOI [10.2139/s...",49,0,...,J IMMIGR REFUG STUD,<NA>,<NA>,<NA>,10.1080/15562948.2022.2132572,WOS:000876581300001,None,None,0,0
1996,1996,"Guo, Y; Xu, JF; Chen, C",Measurement of engagement in the foreign langu...,IRAL-INTERNATIONAL REVIEW OF APPLIED LINGUISTI...,Article; Early Access,CFA; EFL classroom learning; foreign language ...,Huazhong University of Science & Technology; W...,"Aubrey S, 2022, RELC J, V53, P519, DOI 10.1177...",73,3,...,IRAL-INT REV APPL LI,<NA>,<NA>,<NA>,10.1515/iral-2021-0118,WOS:000747993700001,None,None,0,0
1997,1997,"Wang, YB; Liu, FS",Emotional intelligence and second/foreign lang...,LANGUAGE TEACHING RESEARCH,Review; Early Access,emotional intelligence; language learning; met...,Guangdong University of Foreign Studies; Jiang...,"Abdolrezapour P., 2018, CYPRIOT J ED SCI, V13,...",89,0,...,LANG TEACH RES,<NA>,<NA>,<NA>,10.1177/13621688231152627,WOS:000936380600001,None,None,0,0
1998,1998,"Li, JX; Zhang, EH; Zhang, HH; Gou, HC; Cao, HW",Retrieval practice plus feedback benefits a th...,INTERNATIONAL JOURNAL OF MULTILINGUALISM,Article; Early Access,Retrieval practice; testing effect; learning a...,Chongqing University; Shenyang Normal University,"Abel M, 2020, COGNITION, V201, DOI 10.1016/j.c...",67,0,...,INT J MULTILING,<NA>,<NA>,<NA>,10.1080/14790718.2022.2102172,WOS:000831158400001,None,None,0,0
1999,1999,"Calder, SD; Brennan-Jones, CG; Robinson, M; Wh...",How we measure language skills of children at ...,INTERNATIONAL JOURNAL OF SPEECH-LANGUAGE PATHO...,Article; Early Access,Developmental language disorder; identificatio...,University of Tasmania; Curtin University; Tel...,"Adams C., 2001, ASSESSMENT COMPREHEN; American...",53,0,...,INT J SPEECH-LANG PA,<NA>,<NA>,<NA>,10.1080/17549507.2023.2171488,WOS:000935546000001,None,None,0,0

In [5]:
# 各分析单元的引文统计
cm = ComputeMetrics(citation_table, reference_table)
# cm.write2excel('examples/statistics.xlsx')

图文件可以使用 [Graphviz在线编辑器](http://magjac.com/graphviz-visual-editor/) 或本地的 [Graphviz工具](https://graphviz.org/) 生成引文网络图。

In [6]:
# 生成引文网络图文件

doc_indices = citation_table.sort_values('LCS', ascending=False).index[:100] # 选取LSC最高的100篇文献
# doc_indices = primary_table[primary_table['LCS']>5].index # 选取LSC大于5的文献
graph = GraphViz(citation_table).generate_dot_text(doc_indices)
print(graph)

digraph metadata{
	rankdir = BT;
	{rank=same; 1999 68};
	{rank=same; 2000 82 86};
	{rank=same; 2002 120};
	{rank=same; 2003 135 144};
	{rank=same; 2004 161};
	{rank=same; 2005 193};
	{rank=same; 2006 219 240 245 253};
	{rank=same; 2007 273 275 276 288 301};
	{rank=same; 2009 377 381 391};
	{rank=same; 2011 502 513};
	{rank=same; 2012 541 552};
	{rank=same; 2013 599 602 605 609};
	{rank=same; 2014 645 648 662 668 670 673 708};
	{rank=same; 2015 749};
	{rank=same; 2016 821 853 859 875 913};
	{rank=same; 2017 915 927 970 975 977};
	{rank=same; 2019 1176 1177 1217 1225 1263};
	{rank=same; 2020 1337 1344 1360 1402};
	{rank=same; 2021 1449 1471 1487 1494 1534 1568 1636};
	{rank=same; 2022 1791 1810};
	1999 [ shape="plaintext" ];
	2000 [ shape="plaintext" ];
	2002 [ shape="plaintext" ];
	2003 [ shape="plaintext" ];
	2004 [ shape="plaintext" ];
	2005 [ shape="plaintext" ];
	2006 [ shape="plaintext" ];
	2007 [ shape="plaintext" ];
	2009 [ shape="plaintext" ];
	2011 [ shape="plaintext" ];
	2012 [ shape="plaintext" ];
	2013 [ shape="plaintext" ];
	2014 [ shape="plaintext" ];
	2015 [ shape="plaintext" ];
	2016 [ shape="plaintext" ];
	2017 [ shape="plaintext" ];
	2019 [ shape="plaintext" ];
	2020 [ shape="plaintext" ];
	2021 [ shape="plaintext" ];
	2022 [ shape="plaintext" ];
	2022 -> 2021 [ style = invis ];
	2021 -> 2020 [ style = invis ];
	2020 -> 2019 [ style = invis ];
	2019 -> 2017 [ style = invis ];
	2017 -> 2016 [ style = invis ];
	2016 -> 2015 [ style = invis ];
	2015 -> 2014 [ style = invis ];
	2014 -> 2013 [ style = invis ];
	2013 -> 2012 [ style = invis ];
	2012 -> 2011 [ style = invis ];
	2011 -> 2009 [ style = invis ];
	2009 -> 2007 [ style = invis ];
	2007 -> 2006 [ style = invis ];
	2006 -> 2005 [ style = invis ];
	2005 -> 2004 [ style = invis ];
	2004 -> 2003 [ style = invis ];
	2003 -> 2002 [ style = invis ];
	2002 -> 2000 [ style = invis ];
	2000 -> 1999 [ style = invis ];
	135 -> { 120 };
	144 -> { 120 135 };
	161 -> { 135 120 68 };
	193 -> { 120 135 };
	240 -> { 86 };
	273 -> { 135 144 120 82 68 161 };
	381 -> { 301 253 219 275 245 240 };
	599 -> { 161 273 135 };
	605 -> { 552 513 541 288 391 };
	645 -> { 135 273 120 609 301 };
	648 -> { 276 219 };
	668 -> { 135 502 609 273 };
	670 -> { 135 502 273 609 };
	708 -> { 161 135 };
	749 -> { 662 273 };
	821 -> { 502 749 609 273 662 670 135 };
	853 -> { 673 };
	859 -> { 749 662 };
	875 -> { 609 273 135 502 749 };
	913 -> { 273 670 135 };
	927 -> { 377 602 };
	970 -> { 977 };
	975 -> { 662 253 915 301 };
	1176 -> { 970 };
	1217 -> { 977 };
	1225 -> { 977 };
	1263 -> { 970 };
	1337 -> { 1177 1225 };
	1344 -> { 1225 };
	1360 -> { 1225 };
	1449 -> { 970 1225 1217 };
	1471 -> { 1225 135 970 };
	1487 -> { 970 };
	1494 -> { 970 };
	1534 -> { 1360 };
	1568 -> { 1360 1225 977 };
	1791 -> { 1636 1402 1471 1568 };
	1810 -> { 1360 1225 };
}