In [1]:
import os
import pandas as pd
from histcite.process_table import ProcessTable
from histcite.network_graph import GraphViz
from histcite.compute_metrics import ComputeMetrics

In [2]:
# 读取文件，去重，合并
folder_path = 'dataset'
process = ProcessTable(folder_path)
process.concat_table() # 合并多个文件
process.process_citation() # 识别引用关系
docs_table = process.docs_table
reference_table = process.reference_table
docs_table

,doc_index,AU,first_AU,TI,SO,DT,DE,C3,CR,NR,...,J9,PY,VL,BP,DI,UT,reference,citation,LCR,LCS
0,0,"GLAUERT, JRW; KENNAWAY, JR; SLEEP, MR",GLAUERT JRW,DACTL - AN EXPERIMENTAL GRAPH REWRITING LANGUAGE,LECTURE NOTES IN COMPUTER SCIENCE,Article,DACTL; GRAPH REWRITING; COMPUTATIONAL MODEL; P...,University of East Anglia,"BAETEN JCM, 1987, LNCS, V257, P83; BARENDREGT ...",36,...,LECT NOTES COMPUT SC,1991,532,378,<NA>,WOS:A1991LE71500041,None,None,0,0
1,1,"PIELA, PC; EPPERLY, TG; WESTERBERG, KM; WESTER...",PIELA PC,ASCEND - AN OBJECT-ORIENTED COMPUTER ENVIRONME...,COMPUTERS & CHEMICAL ENGINEERING,Article,<NA>,Carnegie Mellon University,"Borning Alan, 1979, THESIS STANFORD U; EPPERLY...",19,...,COMPUT CHEM ENG,1991,15,53,10.1016/0098-1354(91)87006-U,WOS:A1991FA96900006,None,65;78,0,2
2,2,"TEETERS, JL",TEETERS JL,MDL - A SYSTEM FOR FAST SIMULATION OF LARGE LA...,SIMULATION,Article,MODEL DEVELOPMENT LANGUAGE; SIMULATION LANGUAG...,University of Southern California,"Carey R, 1975, THESIS U MASSACHUSET; DESCHUTTE...",14,...,SIMULATION,1991,56,369,10.1177/003754979105600606,WOS:A1991FV44300002,None,None,0,0
3,3,"MCBRIEN, P; NIEZETTE, M; PANTAZIS, D; SELTVEIT...",MCBRIEN P,A RULE LANGUAGE TO CAPTURE AND MODEL BUSINESS ...,LECTURE NOTES IN COMPUTER SCIENCE,Article,<NA>,University of Liege; University of Manchester,"BERZTISS A, 1986, INFORMATION SYSTEM D; BORGID...",23,...,LECT NOTES COMPUT SC,1991,498,307,<NA>,WOS:A1991FW90200015,None,None,0,0
4,4,"Kottemann, JE; Dolk, DR",Kottemann JE,Model Integration and Modeling Languages: A Pr...,INFORMATION SYSTEMS RESEARCH,Article,Model management; Model integration; Modeling ...,University of Michigan System; University of M...,"Blanning R. W., 1986, Decision Support Systems...",25,...,INFORM SYST RES,1992,3,1,10.1287/isre.3.1.1,WOS:000209837400001,None,None,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,1995,"Kanas, A; Kosyakova, Y; Vallizadeh, E",Kanas A,"Linguistic Enclaves, Sorting, and Language Ski...",JOURNAL OF IMMIGRANT & REFUGEE STUDIES,Article; Early Access,Destination language acquisition; linguistic e...,Erasmus University Rotterdam; Otto Friedrich U...,"Aksoy C.G., 2020, SSRN ELECT J, DOI [10.2139/s...",49,...,J IMMIGR REFUG STUD,<NA>,<NA>,<NA>,10.1080/15562948.2022.2132572,WOS:000876581300001,None,None,0,0
1996,1996,"Guo, Y; Xu, JF; Chen, C",Guo Y,Measurement of engagement in the foreign langu...,IRAL-INTERNATIONAL REVIEW OF APPLIED LINGUISTI...,Article; Early Access,CFA; EFL classroom learning; foreign language ...,Huazhong University of Science & Technology; W...,"Aubrey S, 2022, RELC J, V53, P519, DOI 10.1177...",73,...,IRAL-INT REV APPL LI,<NA>,<NA>,<NA>,10.1515/iral-2021-0118,WOS:000747993700001,None,None,0,0
1997,1997,"Wang, YB; Liu, FS",Wang YB,Emotional intelligence and second/foreign lang...,LANGUAGE TEACHING RESEARCH,Review; Early Access,emotional intelligence; language learning; met...,Guangdong University of Foreign Studies; Jiang...,"Abdolrezapour P., 2018, CYPRIOT J ED SCI, V13,...",89,...,LANG TEACH RES,<NA>,<NA>,<NA>,10.1177/13621688231152627,WOS:000936380600001,None,None,0,0
1998,1998,"Li, JX; Zhang, EH; Zhang, HH; Gou, HC; Cao, HW",Li JX,Retrieval practice plus feedback benefits a th...,INTERNATIONAL JOURNAL OF MULTILINGUALISM,Article; Early Access,Retrieval practice; testing effect; learning a...,Chongqing University; Shenyang Normal University,"Abel M, 2020, COGNITION, V201, DOI 10.1016/j.c...",67,...,INT J MULTILING,<NA>,<NA>,<NA>,10.1080/14790718.2022.2102172,WOS:000831158400001,None,None,0,0
1999,1999,"Calder, SD; Brennan-Jones, CG; Robinson, M; Wh...",Calder SD,How we measure language skills of children at ...,INTERNATIONAL JOURNAL OF SPEECH-LANGUAGE PATHO...,Article; Early Access,Developmental language disorder; identificatio...,University of Tasmania; Curtin University; Tel...,"Adams C., 2001, ASSESSMENT COMPREHEN; American...",53,...,INT J SPEECH-LANG PA,<NA>,<NA>,<NA>,10.1080/17549507.2023.2171488,WOS:000935546000001,None,None,0,0

In [3]:
# 基本描述统计
cm = ComputeMetrics(docs_table, reference_table)
cm.write2excel(os.path.join(folder_path,'result','statistics.xlsx'))

图文件可以使用 [Graphviz在线编辑器](http://magjac.com/graphviz-visual-editor/) 或本地的 [Graphviz工具](https://graphviz.org/) 生成引文网络图。

In [4]:
# 生成引文网络图文件

# 选取LSC最高的100篇文献
doc_indices = docs_table.sort_values('LCS', ascending=False).index[:100]

# 选取LSC大于5的文献
# doc_indices = docs_table[citation_table['LCS']>5].index

graph = GraphViz(docs_table)
graph_dot_file = graph.generate_dot_file(doc_indices,allow_external_node=False)

# 保存graph.dot文件
with open(os.path.join(folder_path,'result','graph.dot'),'w') as f:
    f.write(graph_dot_file)
print(graph_dot_file)

digraph metadata{
	rankdir = BT;
	{rank=same; 1997 31};
	{rank=same; 1999 58 68};
	{rank=same; 2000 77 82 86 97};
	{rank=same; 2002 120};
	{rank=same; 2003 135 143 144 149};
	{rank=same; 2004 161 165};
	{rank=same; 2005 193};
	{rank=same; 2006 219 236 240 245 253 254};
	{rank=same; 2007 265 272 273 275 287 288 297 301};
	{rank=same; 2008 317 325};
	{rank=same; 2009 381 389 391 396 410};
	{rank=same; 2010 429};
	{rank=same; 2011 502};
	{rank=same; 2012 541 576};
	{rank=same; 2013 597 609};
	{rank=same; 2014 645 662 670 708};
	{rank=same; 2015 737 739 749 793};
	{rank=same; 2016 821 827 859 875 913};
	{rank=same; 2017 915 926 975 992};
	{rank=same; 2019 1177 1178};
	{rank=same; 2020 1311 1337};
	1997 [ shape="plaintext" ];
	1999 [ shape="plaintext" ];
	2000 [ shape="plaintext" ];
	2002 [ shape="plaintext" ];
	2003 [ shape="plaintext" ];
	2004 [ shape="plaintext" ];
	2005 [ shape="plaintext" ];
	2006 [ shape="plaintext" ];
	2007 [ shape="plaintext" ];
	2008 [ shape="plaintext" ];
	2009 [ shape="plaintext" ];
	2010 [ shape="plaintext" ];
	2011 [ shape="plaintext" ];
	2012 [ shape="plaintext" ];
	2013 [ shape="plaintext" ];
	2014 [ shape="plaintext" ];
	2015 [ shape="plaintext" ];
	2016 [ shape="plaintext" ];
	2017 [ shape="plaintext" ];
	2019 [ shape="plaintext" ];
	2020 [ shape="plaintext" ];
	2020 -> 2019 [ style = invis ];
	2019 -> 2017 [ style = invis ];
	2017 -> 2016 [ style = invis ];
	2016 -> 2015 [ style = invis ];
	2015 -> 2014 [ style = invis ];
	2014 -> 2013 [ style = invis ];
	2013 -> 2012 [ style = invis ];
	2012 -> 2011 [ style = invis ];
	2011 -> 2010 [ style = invis ];
	2010 -> 2009 [ style = invis ];
	2009 -> 2008 [ style = invis ];
	2008 -> 2007 [ style = invis ];
	2007 -> 2006 [ style = invis ];
	2006 -> 2005 [ style = invis ];
	2005 -> 2004 [ style = invis ];
	2004 -> 2003 [ style = invis ];
	2003 -> 2002 [ style = invis ];
	2002 -> 2000 [ style = invis ];
	2000 -> 1999 [ style = invis ];
	1999 -> 1997 [ style = invis ];
	58 -> { 31 };
	68 -> { 31 58 };
	82 -> { 77 58 };
	135 -> { 120 };
	144 -> { 120 135 };
	161 -> { 135 120 68 };
	193 -> { 120 135 };
	219 -> { 143 };
	236 -> { 68 };
	240 -> { 86 };
	253 -> { 143 };
	254 -> { 143 };
	265 -> { 165 };
	272 -> { 135 };
	273 -> { 135 144 120 82 68 161 };
	275 -> { 143 };
	287 -> { 97 };
	297 -> { 82 };
	301 -> { 253 };
	317 -> { 143 240 };
	381 -> { 301 253 219 275 245 240 };
	396 -> { 77 };
	410 -> { 325 };
	429 -> { 135 272 };
	502 -> { 389 };
	541 -> { 288 391 };
	576 -> { 410 };
	597 -> { 253 };
	609 -> { 389 };
	645 -> { 135 273 120 609 301 };
	662 -> { 273 };
	670 -> { 135 502 273 609 };
	708 -> { 161 135 };
	739 -> { 149 135 273 240 82 219 };
	749 -> { 662 273 };
	821 -> { 502 749 609 273 662 670 135 };
	827 -> { 149 381 301 253 };
	859 -> { 749 662 };
	875 -> { 609 273 135 502 749 };
	913 -> { 273 670 135 };
	915 -> { 396 135 381 301 };
	926 -> { 273 913 135 };
	975 -> { 662 253 915 827 301 };
	992 -> { 793 };
	1177 -> { 165 };
	1178 -> { 793 };
	1311 -> { 737 265 };
	1337 -> { 1177 };
}

In [5]:
# 导出图节点文件
graph_node_file = graph.generate_graph_node_file()
graph_node_file.to_excel(os.path.join(folder_path,'result','graph.node.xlsx'),index=False)
graph_node_file

,doc_index,AU,PY,SO,VL,BP,LCS,GCS
31,31,Iyer R,1997,IEEE SIGNAL PROCESSING LETTERS,4,221,5,24
58,58,Iyer RM,1999,IEEE TRANSACTIONS ON SPEECH AND AUDIO PROCESSING,7,30,10,55
68,68,Iver R,1999,COMPUTER SPEECH AND LANGUAGE,13,267,7,14
77,77,Bellegarda JR,2000,IEEE TRANSACTIONS ON SPEECH AND AUDIO PROCESSING,8,76,7,43
82,82,Bellegarda JR,2000,PROCEEDINGS OF THE IEEE,88,1279,15,210
...,...,...,...,...,...,...,...,...
992,992,Hellendoorn VJ,2017,ESEC/FSE 2017: PROCEEDINGS OF THE 2017 11TH JO...,<NA>,763,4,135
1177,1177,Huang J,2019,IEEE TRANSACTIONS ON CIRCUITS AND SYSTEMS FOR ...,29,2822,5,69
1178,1178,Nguyen S,2019,34TH IEEE/ACM INTERNATIONAL CONFERENCE ON AUTO...,<NA>,722,2,0
1311,1311,Sridhar A,2020,MM '20: PROCEEDINGS OF THE 28TH ACM INTERNATIO...,<NA>,1366,2,9
1337,1337,Sincan OM,2020,IEEE ACCESS,8,181340,2,23